### ISSUE TITLE
BootLoop Issue

### ISSUE THREAD

**Issue by MikeGG1993** [BiTGApps/aosp-build#1]
Followed the whole guide, build on Android 12, successfully built but ROM enters bootloop, Anyone have any idea?

**Comment by TheHitMan7** [comment]
Grab logcat.

**Comment by MikeGG1993** [comment]
Ok, so built the Android 12 ROM for pixel 3 with bitgapps, it went to bootloop, I tried to pull the logcat, but that doesn't work too. I will try one more time for the logcat.

**Comment by ConradGyllenhaal** [comment]
I'm able to build AOSP for Pixel 3 (blueline) while integrating this project (aosp-build) and no problem at all.

Your problem must be somewhere else.
