### ISSUE TITLE
Disable Privileged Permission Allowlisting

### ISSUE THREAD

**Issue by ConradGyllenhaal** [BiTGApps/aosp-build#2]
Hello there,

Since you deleted this repository and recreate it on 24th of october 2021, we can't see the history.

Using the latest commit of yours, I have now an error that I didn't have before.

It's related to ro.control_privapp_permissions property that you set to disable.

Here is the message error when building AOSP 12.0 for sunfish device (Pixel 4a):
`error: found duplicate sysprop assignments:                                                                           
ro.control_privapp_permissions=enforce                                                                                
ro.control_privapp_permissions=disable`

The build stops there.

It seems to collude with "ro.control_privapp_permissions=enforce" set by AOSP (in device/google/sunfish/device.mk) but also from the Google extracted binaries (thanks to android-prepare-vendor project) in vendor/build.prop for example

Anyway, since you restrain some Google Apps to less privileges, I think you also should enforce this restriction, no?

**Comment by ConradGyllenhaal** [comment]
Just out of curiosity, can you explain why you did set up this property?

It seems to defeat your purpose of narrowing down the Google Apps permissions.

"ro.control_privapp_permissions=disable" disables the check of the priv-app permissions XML files, and thus, disable the protection, no?

**Comment by TheHitMan7** [comment]
> Just out of curiosity, can you explain why you did set up this property?

Someone reported bootloop after building with BiTGApps AOSP Build System, it might be permission issue, so have to setup this temporarily until fixed.

Well i didn't get any further report and property remain as is.

**Comment by ConradGyllenhaal** [comment]
I can assure you that I don't get any bootloop when I comment this line out and run the system after build and flash.

However, it indeed prevents building AOSP when present.

**Comment by TheHitMan7** [comment]
> However, it indeed prevents building AOSP when present.

I will revert that change soon till then comment out [here](https://github.com/BiTGApps/aosp-build/blob/master/gapps.mk#L68) to fix this issue.

**Comment by TheHitMan7** [comment]
@ConradGyllenhaal

Re-enabled Privileged Permission https://github.com/BiTGApps/aosp-build/commit/c1499edc6d484260f860b1fe2798d63cf3899d97.
