### ISSUE TITLE
Error when using Signal

### ISSUE THREAD

**Issue by ConradGyllenhaal** [BiTGApps/aosp-build#3]
Hello there,

On a Pixel 4a running AOSP 11 and your bitgapps included thanks to aosp_build project.

I don't log-in on any Google account. I'm installing needed apps via Aurora Store.

However, I got an error Activity when I register a Signal account ([here is the Activity displayed](https://github.com/signalapp/Signal-Android/blob/44d014c4459e9ac34b74800002fa86b402d0501c/app/src/main/java/org/thoughtcrime/securesms/PlayServicesProblemActivity.java)).

I also got an error notification on earch start of Signal, complaining of the lack of Google Play Services on the device (despite being able to use the Google Play Store, Google geolocation and so...)

Looking at the source code of Signal, it seems to be linked to this [test](https://github.com/signalapp/Signal-Android/blob/a5e5a735800cbdb3afa01a67390b6efa2fc91be6/app/src/main/java/org/thoughtcrime/securesms/jobs/FcmRefreshJob.java#L85)

Do you have an idea why this check doesn't complete while using BitGApps?

Kind regards

**Comment by TheHitMan7** [comment]
Try manually updating Google Play Services using APK.

**Comment by ConradGyllenhaal** [comment]
> Try manually updating Google Play Services using APK.

I did that, got an update, and now that the Play Services are fully up-to-date, I'm still receiving the same error.

I have now moved to AOSP 12, but the error is exactly the same.

Please tell me if you need any logs to understand this better.
